"""empty message

Revision ID: 987838667228
Revises: be0f84a709de
Create Date: 2020-09-13 22:45:36.493073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987838667228'
down_revision = 'be0f84a709de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'traditional_auth', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traditional_auth', type_='unique')
    # ### end Alembic commands ###
